name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install shellcheck & shfmt
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck shfmt

      - name: Run shellcheck (non-blocking)
        run: |
          shellcheck c2-client.sh moduless.sh funcmgr.sh modules.d/* || true

      - name: Run shfmt (check only, non-blocking)
        run: |
          # Check formatting for specific scripts only
          shfmt -d c2-client.sh moduless.sh funcmgr.sh modules.d/* || echo "Shfmt formatting issues found. Run 'shfmt -w <file>' to fix."
